const path = require('path');
const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const isAdmin = require('../middleware/is-admin');
const accountController = require('../controller/account');
router.get('/addlorirent',isAdmin, accountController.addlorirent);
router.post('/addlorirent',isAdmin, accountController.postaddlorirent);
router.post('/addloripayment',isAdmin, accountController.addloripayment);
router.post('/fliteraddlorirent',isAdmin, accountController.fliteraddlorirent);
router.get('/addindividuallorirent/:id',isAdmin, accountController.addindividuallorirent);
router.post('/fliterindividualaddlorirent',isAdmin, accountController.fliterindividualaddlorirent);
router.get('/deleteloarirent/:objectid/:id/:section',isAdmin, accountController.deleteloarirent);
router.get('/deleteloaripayment/:objectid/:id/:section',isAdmin, accountController.deleteloaripayment);
router.post('/filterutility',isAdmin, accountController.filterutility);
router.get('/indivual_utility/:id',isAdmin, accountController.indivual_utility);
router.get('/deleteutility/:objectid/:id/:section',isAdmin, accountController.deleteutility);
router.post('/filterindividualutility',isAdmin, accountController.filterindividualutility);
router.get('/getpayments',isAdmin, accountController.getpayments);
router.post('/getpayments',isAdmin, accountController.postpaid);
router.post('/paidamountform',isAdmin, accountController.paidamountform);
router.get('/individualpayments/:id',isAdmin, accountController.individualpayments);
router.post('/filterpayments',isAdmin, accountController.filterpayments);
router.post('/filterindividualpayments',isAdmin, accountController.filterindividualpayments);
router.get('/deletepaid/:objectid/:id/:section',isAdmin, accountController.deletepaid);
router.get('/deletepayment/:objectid/:id/:section',isAdmin, accountController.deletepayment);
module.exports = router;