const path = require('path');
const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const isAdmin = require('../middleware/is-admin');
const borrowcontroller = require('../controller/borrows_salary');
router.get('/borrows',isAdmin, borrowcontroller.borrows);
router.post('/borrows',isAdmin, borrowcontroller.borrowform);
router.get('/indivdualborrows/:id',isAdmin, borrowcontroller.indivdualborrows);
router.post('/filterborrows',isAdmin, borrowcontroller.filterborrows);
router.post('/indivdualborrowsfilter',isAdmin, borrowcontroller.indivdualborrowsfilter);
router.get('/deleteborrow/:objectid/:arrayid/:section',isAdmin, borrowcontroller.deleteborrow);
router.get('/salary',isAdmin, borrowcontroller.salary);
router.post('/salary',isAdmin, borrowcontroller.salaryform);
router.get('/indivdualsalary/:id',isAdmin, borrowcontroller.indivdualsalary);
router.get('/deletesalary/:objectid/:arrayid/:section',isAdmin, borrowcontroller.deletesalary);
router.get('/deletesalarypayment/:objectid/:arrayid/:section',isAdmin, borrowcontroller.deletesalarypayment);
router.post('/filtersalary',isAdmin, borrowcontroller.filtersalary);
router.post('/indivdualsalaryfilter',isAdmin, borrowcontroller.indivdualsalaryfilter);
router.post('/addsalary',isAdmin, borrowcontroller.addsalary);
module.exports = router;