const path = require('path');
const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const isAdmin = require('../middleware/is-admin');
const isMorA = require('../middleware/is-mora');
const employeeController = require('../controller/employee');
router.get('/viewkooli',isMorA, employeeController.viewkooli);
router.post('/viewkoolifilter',isMorA, employeeController.koolifilter);
router.get('/viewkooli/:id',isMorA, employeeController.individualloads);
router.post('/individualloadsfilter',isMorA, employeeController.individualloadsfilter);
router.get('/indidualkooli/:id',isMorA, employeeController.indidualkooli);
router.get('/deleteload/:id/:name',isMorA, employeeController.deleteload);
router.post('/indidualkoolifilter',isMorA, employeeController.indidualkoolifilter);
router.post('/addloaderpayment',isAdmin, employeeController.addloaderpayment);
router.get('/deletepayment/:arrayid/:name/:type',isAdmin, employeeController.deletepayment);
router.get('/viewattendance',isMorA, employeeController.viewattendance);
router.get('/viewattendance/:id',isMorA, employeeController.viewattendanceperson);
router.post('/viewattendanceindividual',isMorA, employeeController.viewattendanceindividual);
router.post('/viewattendancefilter',isMorA, employeeController.viewattendancefilter);
router.get('/Editemployee',isAdmin, employeeController.Editemployee);
router.post('/Editemployee',isAdmin, employeeController.PostEditemployee);
router.get('/deleteemployee/:id',isAdmin, employeeController.deleteemployee);
router.post('/postaddemployee',isAdmin, employeeController.postaddemployee);
router.get('/markattendance',isMorA, employeeController.markattendance);
router.post('/markattendance',isMorA, employeeController.postmarkattendance);
router.get('/addkooli',isMorA, employeeController.addkooli);
router.post('/addkooli',isMorA, employeeController.postaddkooli);
router.get('/loaderspayment',isAdmin, employeeController.loaderspayment);
router.post('/filterloaderspayment',isAdmin, employeeController.filterloaderspayment);
module.exports = router;