const path = require('path');
const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const isAdmin = require('../middleware/is-admin');
const employeeController = require('../controller/employee');
router.get('/viewkooli',isAdmin, employeeController.viewkooli);
router.post('/viewkoolifilter',isAdmin, employeeController.koolifilter);
router.get('/viewkooli/:id',isAdmin, employeeController.individualloads);
router.post('/individualloadsfilter',isAdmin, employeeController.individualloadsfilter);
router.get('/indidualkooli/:id',isAdmin, employeeController.indidualkooli);
router.get('/deleteload/:id/:name',isAdmin, employeeController.deleteload);
router.post('/indidualkoolifilter',isAdmin, employeeController.indidualkoolifilter);
router.post('/addloaderpayment',isAdmin, employeeController.addloaderpayment);
router.get('/deletepayment/:arrayid/:name/:type',isAdmin, employeeController.deletepayment);
router.get('/viewattendance',isAdmin, employeeController.viewattendance);
router.get('/viewattendance/:id',isAdmin, employeeController.viewattendanceperson);
router.post('/viewattendanceindividual',isAdmin, employeeController.viewattendanceindividual);
router.post('/viewattendancefilter',isAdmin, employeeController.viewattendancefilter);
router.get('/Editemployee',isAdmin, employeeController.Editemployee);
router.post('/Editemployee',isAdmin, employeeController.PostEditemployee);
router.get('/deleteemployee/:id',isAdmin, employeeController.deleteemployee);
router.post('/postaddemployee',isAdmin, employeeController.postaddemployee);
router.get('/markattendance',isAdmin, employeeController.markattendance);
router.post('/markattendance',isAdmin, employeeController.postmarkattendance);
router.get('/addkooli',isAdmin, employeeController.addkooli);
router.post('/addkooli',isAdmin, employeeController.postaddkooli);
router.get('/loaderspayment',isAdmin, employeeController.loaderspayment);
router.post('/filterloaderspayment',isAdmin, employeeController.filterloaderspayment);
module.exports = router;