const path = require('path');
const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const mainList = require('../controller/list');
const isAdmin = require('../middleware/is-admin');
router.get('/dealerslist',isAdmin, mainList.dealerslist);
router.get('/payeelist',isAdmin, mainList.payeelist);
router.get('/borrowlist',isAdmin, mainList.borrowlist);
router.get('/lorilist',isAdmin, mainList.rentlist);
router.get('/loaderslist',isAdmin, mainList.loaderslist);
module.exports = router;
