const path = require('path');
const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const mainList = require('../controller/list');
const isAdmin = require('../middleware/is-admin');
router.get('/dealerslist',isAdmin, mainList.dealerslist);
router.post('/deletedealersales',isAdmin, mainList.deletedealersales);
router.post('/deletedealerpurchase',isAdmin, mainList.deletedealerpurchase);
router.get('/payeelist',isAdmin, mainList.payeelist);
router.get('/borrowlist',isAdmin, mainList.borrowlist);
router.get('/lorilist',isAdmin, mainList.rentlist);
router.get('/loaderslist',isAdmin, mainList.loaderslist);
router.get('/deleteloader/:id',isAdmin, mainList.deleteloader);
router.get('/deleteloari/:id',isAdmin, mainList.deleteloari);
module.exports = router;
